# Generated by Django 5.1.1 on 2024-10-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamusermodel',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='teamusermodel',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='teamusermodel',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='teamusermodel',
            name='first_name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='teamusermodel',
            name='first_name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='teamusermodel',
            name='first_name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='teamusermodel',
            name='last_name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='teamusermodel',
            name='last_name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='teamusermodel',
            name='last_name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='teamusermodel',
            name='role_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='teamusermodel',
            name='role_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='teamusermodel',
            name='role_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Role'),
        ),
    ]
