# Generated by Django 5.1.1 on 2024-10-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_users', '0002_teamusermodel_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamusermodel',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='teamusermodel',
            name='first_name_ru',
        ),
        migrations.RemoveField(
            model_name='teamusermodel',
            name='last_name_ru',
        ),
        migrations.RemoveField(
            model_name='teamusermodel',
            name='role_ru',
        ),
    ]
