# Generated by Django 5.1.1 on 2024-10-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(default='files/default_avatar.jpeg', upload_to='users/', verbose_name='Avatar'),
        ),
    ]
