# Generated by Django 5.1.1 on 2024-10-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='full_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='full_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='full_name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Full Name'),
        ),
    ]
