# Generated by Django 5.1.1 on 2024-10-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermodel_full_name_en_usermodel_full_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='full_name_ru',
        ),
    ]
