# Generated by Django 5.1.1 on 2024-10-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_usermodel_full_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='confirm_password',
            field=models.CharField(default=False, max_length=100, verbose_name='Confirm Password'),
            preserve_default=False,
        ),
    ]
