# Generated by Django 5.1.1 on 2024-10-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usermodel_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='confirm_password',
        ),
    ]
