# Generated by Django 5.1.1 on 2024-10-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_usermodel_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_avatars/', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
    ]
