# Generated by Django 5.1.1 on 2024-10-10 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usermodel_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='status',
            new_name='is_active',
        ),
    ]
