# Generated by Django 5.1.1 on 2024-10-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_usermodel_last_login_alter_usermodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='username',
            field=models.CharField(default=None, max_length=100, unique=True, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
