# Generated by Django 5.1.1 on 2024-10-13 05:00

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_usermodel_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(blank=True, default='https://i.pinimg.com/736x/6a/d8/6f/6ad86fe68e2f55f29a0bf1a92d26a221.jpg', null=True, upload_to='team_avatars/', validators=[users.models.validate_image_size], verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Password'),
        ),
    ]
