# Generated by Django 5.1.1 on 2024-10-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_usermodel_created_at_remove_usermodel_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='full_name_en',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='full_name_uz',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(default=None, max_length=100, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='first_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='first_name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(default=None, max_length=100, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='last_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='last_name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Password'),
        ),
    ]
