# Generated by Django 5.1.1 on 2024-10-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_feedbackmodel_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='title_ru',
        ),
    ]
