# Generated by Django 5.1.1 on 2024-10-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_remove_feedbackmodel_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
