# Generated by Django 5.1.1 on 2024-10-11 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0004_alter_feedbackmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='likes',
        ),
    ]
